<%@ Page Title="" Language="C#" MasterPageFile="~/Site1.Master" AutoEventWireup="true" CodeBehind="rounds.aspx.cs" Inherits="FifaGame.WebForm6" %>
<asp:Content ID="Content1" ContentPlaceHolderID="ContentPlaceHolder1" runat="server">
    
     <form id="form1" runat="server">

          <asp:GridView ID="GridView1" runat="server"  AutoGenerateColumns="false"
              BorderColor="#999999" BorderStyle="None" BorderWidth="1px" CellPadding="3" GridLines="Vertical"
              AutoGenerateDeleteButton="True"
              AutoGenerateEditButton="True" 
              OnRowEditing="GridView1_RowEditing"
              OnRowCancelingEdit ="GridView1_RowCancelingEdit"
              OnRowDeleting="GridView1_RowDeleting"
              OnRowUpdating="GridView1_RowUpdating"
              
              DataKeyNames="round_id">
                  <Columns>
                          <asp:BoundField DataField="round_id" HeaderText ="Round_Id" />
                    <asp:BoundField DataField="user_id1" HeaderText ="First_Player_id" />
                    <asp:BoundField DataField="user_id2" HeaderText ="Second_Player_id" />
                       <asp:BoundField DataField="compitition_id" HeaderText ="Competition_id" />
                       <asp:BoundField DataField="date" HeaderText ="Date" />
                       <asp:BoundField DataField="winner_id" HeaderText ="Winner_id" />
                       <asp:BoundField DataField="loser_id" HeaderText ="Loser_id" />
                         <asp:BoundField DataField="user_name1" HeaderText ="First_Player_Name" />
                       <asp:BoundField DataField="user_name2" HeaderText ="Second_Player_Name" />
                  </Columns>
        </asp:GridView>
       <table border="1" cellpadding="0" cellspacing="0" style="border-collapse: collapse">
            <tr>
                <td style="width: 150px">
                    First_Player_ID:<br />
                    <asp:TextBox ID="First_PlayerTxt" runat="server" Width="140" />
                </td>
                <td style="width: 150px">
                    Second_Player_ID:<br />
                    <asp:TextBox ID="Second_PlayerTxt" runat="server" Width="140" />
                </td>
                <td style="width: 150px">
                    First_Player_Name:<br />
                    <asp:TextBox ID="FirstPlayerNameText" runat="server" Width="140" />
                </td>
                <td style="width: 150px">
                    Second_Player_Name:<br />
                    <asp:TextBox ID="SecondPlayerNameText" runat="server" Width="140" />
                </td>
                  <td style="width: 150px">
                    Competition_id:<br />
                    <asp:TextBox ID="Competition_idTxt" runat="server" Width="140" />
                </td>
                  <td style="width: 150px">
                    Date:<br />
                    <asp:TextBox ID="DateTxt" runat="server" Width="140" />
                </td>
                  <td style="width: 150px">
                    Winner_id:<br />
                    <asp:TextBox ID="Winner_idTxt" runat="server" Width="140" />
                </td>
                  <td style="width: 150px">
                    Loser_id:<br />
                    <asp:TextBox ID="Loser_idTxt" runat="server" Width="140" />
                </td>
            
                <td style="width: 150px">
                    <asp:Button ID="btnAdd" runat="server" Text="Add New * " OnClick="btnAdd_Click"/>
                </td>
            </tr>
        </table>
          <br />
      </form>
</asp:Content>
